// <auto-generated />
using System;
using CareerPlatform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerPlatform.Domain.Entities.CareerPath", b =>
                {
                    b.Property<int>("CareerPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CareerPathId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CareerPathId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CareerPaths", (string)null);

                    b.HasData(
                        new
                        {
                            CareerPathId = 1,
                            Description = "Builds server-side applications, APIs, databases, and integrations.",
                            Name = "Backend Developer"
                        },
                        new
                        {
                            CareerPathId = 2,
                            Description = "Builds user interfaces and client-side web experiences.",
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            CareerPathId = 3,
                            Description = "Builds both frontend and backend parts of web applications.",
                            Name = "Full Stack Developer"
                        },
                        new
                        {
                            CareerPathId = 4,
                            Description = "Builds mobile applications for Android, iOS, or cross-platform environments.",
                            Name = "Mobile Developer"
                        },
                        new
                        {
                            CareerPathId = 5,
                            Description = "Automates deployment, infrastructure, monitoring, and delivery workflows.",
                            Name = "DevOps Engineer"
                        },
                        new
                        {
                            CareerPathId = 6,
                            Description = "Builds data pipelines, storage systems, and analytical data platforms.",
                            Name = "Data Engineer"
                        },
                        new
                        {
                            CareerPathId = 7,
                            Description = "Builds applications and systems powered by machine learning and AI models.",
                            Name = "AI Engineer"
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("ChatMessages", (string)null);

                    b.HasData(
                        new
                        {
                            MessageId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "How should I continue learning backend development?",
                            CreatedAt = new DateTime(2026, 1, 4, 9, 1, 0, 0, DateTimeKind.Utc),
                            Role = "User",
                            SessionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            MessageId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "Focus next on Object Oriented Programming, JWT Authentication, and Docker Basics to round out your backend roadmap.",
                            CreatedAt = new DateTime(2026, 1, 4, 9, 2, 0, 0, DateTimeKind.Utc),
                            Role = "Assistant",
                            SessionId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions", (string)null);

                    b.HasData(
                        new
                        {
                            SessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.LearningResource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResourceId"));

                    b.Property<int>("SkillNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ResourceId");

                    b.HasIndex("SkillNodeId");

                    b.ToTable("LearningResources", (string)null);

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            SkillNodeId = 1,
                            Title = "Microsoft Learn C#",
                            Url = "https://learn.microsoft.com/dotnet/csharp/"
                        },
                        new
                        {
                            ResourceId = 2,
                            SkillNodeId = 1,
                            Title = "FreeCodeCamp C# Tutorial",
                            Url = "https://www.freecodecamp.org/news/tag/c-sharp/"
                        },
                        new
                        {
                            ResourceId = 3,
                            SkillNodeId = 2,
                            Title = "Microsoft OOP Concepts",
                            Url = "https://learn.microsoft.com/dotnet/csharp/fundamentals/tutorials/oop"
                        },
                        new
                        {
                            ResourceId = 4,
                            SkillNodeId = 2,
                            Title = "Object Oriented Programming in C#",
                            Url = "https://learn.microsoft.com/dotnet/csharp/fundamentals/object-oriented/"
                        },
                        new
                        {
                            ResourceId = 5,
                            SkillNodeId = 3,
                            Title = "Microsoft ASP.NET Core Documentation",
                            Url = "https://learn.microsoft.com/aspnet/core/"
                        },
                        new
                        {
                            ResourceId = 6,
                            SkillNodeId = 3,
                            Title = "ASP.NET Core Web API Tutorial",
                            Url = "https://learn.microsoft.com/aspnet/core/tutorials/first-web-api"
                        },
                        new
                        {
                            ResourceId = 7,
                            SkillNodeId = 4,
                            Title = "SQL Server Documentation",
                            Url = "https://learn.microsoft.com/sql/sql-server/"
                        },
                        new
                        {
                            ResourceId = 8,
                            SkillNodeId = 4,
                            Title = "SQL Server Tutorial",
                            Url = "https://learn.microsoft.com/sql/t-sql/tutorial-writing-transact-sql-statements"
                        },
                        new
                        {
                            ResourceId = 9,
                            SkillNodeId = 5,
                            Title = "REST API Design Guidance",
                            Url = "https://learn.microsoft.com/azure/architecture/best-practices/api-design"
                        },
                        new
                        {
                            ResourceId = 10,
                            SkillNodeId = 5,
                            Title = "HTTP Methods and Status Codes",
                            Url = "https://developer.mozilla.org/docs/Web/HTTP"
                        },
                        new
                        {
                            ResourceId = 11,
                            SkillNodeId = 6,
                            Title = "JWT Authentication in ASP.NET Core",
                            Url = "https://learn.microsoft.com/aspnet/core/security/authentication/"
                        },
                        new
                        {
                            ResourceId = 12,
                            SkillNodeId = 6,
                            Title = "JSON Web Tokens Introduction",
                            Url = "https://jwt.io/introduction"
                        },
                        new
                        {
                            ResourceId = 13,
                            SkillNodeId = 7,
                            Title = "Docker Get Started",
                            Url = "https://docs.docker.com/get-started/"
                        },
                        new
                        {
                            ResourceId = 14,
                            SkillNodeId = 7,
                            Title = "Docker for .NET Developers",
                            Url = "https://learn.microsoft.com/dotnet/architecture/microservices/container-docker-introduction/"
                        },
                        new
                        {
                            ResourceId = 15,
                            SkillNodeId = 8,
                            Title = "MDN HTML Guide",
                            Url = "https://developer.mozilla.org/docs/Web/HTML"
                        },
                        new
                        {
                            ResourceId = 16,
                            SkillNodeId = 8,
                            Title = "FreeCodeCamp HTML Tutorial",
                            Url = "https://www.freecodecamp.org/news/tag/html/"
                        },
                        new
                        {
                            ResourceId = 17,
                            SkillNodeId = 9,
                            Title = "MDN CSS Guide",
                            Url = "https://developer.mozilla.org/docs/Web/CSS"
                        },
                        new
                        {
                            ResourceId = 18,
                            SkillNodeId = 9,
                            Title = "Web.dev Learn CSS",
                            Url = "https://web.dev/learn/css"
                        },
                        new
                        {
                            ResourceId = 19,
                            SkillNodeId = 10,
                            Title = "MDN JavaScript Guide",
                            Url = "https://developer.mozilla.org/docs/Web/JavaScript/Guide"
                        },
                        new
                        {
                            ResourceId = 20,
                            SkillNodeId = 10,
                            Title = "JavaScript.info",
                            Url = "https://javascript.info/"
                        },
                        new
                        {
                            ResourceId = 21,
                            SkillNodeId = 11,
                            Title = "TypeScript Handbook",
                            Url = "https://www.typescriptlang.org/docs/handbook/intro.html"
                        },
                        new
                        {
                            ResourceId = 22,
                            SkillNodeId = 11,
                            Title = "TypeScript for JavaScript Programmers",
                            Url = "https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html"
                        },
                        new
                        {
                            ResourceId = 23,
                            SkillNodeId = 12,
                            Title = "React Official Documentation",
                            Url = "https://react.dev/"
                        },
                        new
                        {
                            ResourceId = 24,
                            SkillNodeId = 12,
                            Title = "React Crash Course",
                            Url = "https://www.freecodecamp.org/news/react-crash-course/"
                        },
                        new
                        {
                            ResourceId = 25,
                            SkillNodeId = 13,
                            Title = "React Router Documentation",
                            Url = "https://reactrouter.com/"
                        },
                        new
                        {
                            ResourceId = 26,
                            SkillNodeId = 13,
                            Title = "React Router Tutorial",
                            Url = "https://reactrouter.com/en/main/start/tutorial"
                        },
                        new
                        {
                            ResourceId = 27,
                            SkillNodeId = 14,
                            Title = "Axios Documentation",
                            Url = "https://axios-http.com/docs/intro"
                        },
                        new
                        {
                            ResourceId = 28,
                            SkillNodeId = 14,
                            Title = "Fetch API Guide",
                            Url = "https://developer.mozilla.org/docs/Web/API/Fetch_API/Using_Fetch"
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.PortfolioProject", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TechStack")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "GithubUrl")
                        .IsUnique();

                    b.ToTable("PortfolioProjects", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "A career orientation and learning roadmap platform built with ASP.NET Core and React.",
                            GithubUrl = "https://github.com/demo/CareerPlatform",
                            ImportedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RepositoryName = "CareerPlatform",
                            TechStack = "ASP.NET Core, EF Core, SQL Server, React",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProjectId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "A practice backend API project with authentication, CRUD endpoints, and SQL Server persistence.",
                            GithubUrl = "https://github.com/demo/BackendApiPractice",
                            ImportedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            RepositoryName = "BackendApiPractice",
                            TechStack = "C#, ASP.NET Core, SQL Server",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.RoadmapProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SkillNodeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProgressId");

                    b.HasIndex("SkillNodeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SkillNodeId")
                        .IsUnique();

                    b.ToTable("RoadmapProgresses", (string)null);

                    b.HasData(
                        new
                        {
                            ProgressId = 1,
                            CompletedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            SkillNodeId = 1,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProgressId = 2,
                            CompletedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            SkillNodeId = 3,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProgressId = 3,
                            IsCompleted = false,
                            SkillNodeId = 4,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.SkillNode", b =>
                {
                    b.Property<int>("SkillNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillNodeId"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SkillNodeId");

                    b.HasIndex("CareerPathId");

                    b.HasIndex("CareerPathId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("SkillNodes", (string)null);

                    b.HasData(
                        new
                        {
                            SkillNodeId = 1,
                            CareerPathId = 1,
                            Description = "Learn C# syntax, types, collections, and language fundamentals.",
                            Difficulty = 1,
                            DisplayOrder = 1,
                            EstimatedHours = 20,
                            Name = "C#"
                        },
                        new
                        {
                            SkillNodeId = 2,
                            CareerPathId = 1,
                            Description = "Understand classes, interfaces, inheritance, encapsulation, and polymorphism.",
                            Difficulty = 1,
                            DisplayOrder = 2,
                            EstimatedHours = 16,
                            Name = "Object Oriented Programming"
                        },
                        new
                        {
                            SkillNodeId = 3,
                            CareerPathId = 1,
                            Description = "Build backend applications and APIs with ASP.NET Core.",
                            Difficulty = 2,
                            DisplayOrder = 3,
                            EstimatedHours = 24,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillNodeId = 4,
                            CareerPathId = 1,
                            Description = "Design relational schemas and query data with SQL Server.",
                            Difficulty = 1,
                            DisplayOrder = 4,
                            EstimatedHours = 18,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillNodeId = 5,
                            CareerPathId = 1,
                            Description = "Design RESTful endpoints, status codes, validation, and error responses.",
                            Difficulty = 2,
                            DisplayOrder = 5,
                            EstimatedHours = 16,
                            Name = "REST API"
                        },
                        new
                        {
                            SkillNodeId = 6,
                            CareerPathId = 1,
                            Description = "Implement token-based authentication and role-based authorization.",
                            Difficulty = 2,
                            DisplayOrder = 6,
                            EstimatedHours = 16,
                            Name = "JWT Authentication"
                        },
                        new
                        {
                            SkillNodeId = 7,
                            CareerPathId = 1,
                            Description = "Learn container fundamentals for packaging and running backend applications.",
                            Difficulty = 1,
                            DisplayOrder = 7,
                            EstimatedHours = 12,
                            Name = "Docker Basics"
                        },
                        new
                        {
                            SkillNodeId = 8,
                            CareerPathId = 2,
                            Description = "Structure web pages with semantic HTML.",
                            Difficulty = 1,
                            DisplayOrder = 1,
                            EstimatedHours = 10,
                            Name = "HTML"
                        },
                        new
                        {
                            SkillNodeId = 9,
                            CareerPathId = 2,
                            Description = "Style responsive layouts with CSS fundamentals.",
                            Difficulty = 1,
                            DisplayOrder = 2,
                            EstimatedHours = 14,
                            Name = "CSS"
                        },
                        new
                        {
                            SkillNodeId = 10,
                            CareerPathId = 2,
                            Description = "Learn JavaScript syntax, DOM interaction, and asynchronous programming.",
                            Difficulty = 1,
                            DisplayOrder = 3,
                            EstimatedHours = 22,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillNodeId = 11,
                            CareerPathId = 2,
                            Description = "Add static typing and safer structure to JavaScript applications.",
                            Difficulty = 2,
                            DisplayOrder = 4,
                            EstimatedHours = 16,
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillNodeId = 12,
                            CareerPathId = 2,
                            Description = "Build component-based user interfaces with React.",
                            Difficulty = 2,
                            DisplayOrder = 5,
                            EstimatedHours = 24,
                            Name = "React"
                        },
                        new
                        {
                            SkillNodeId = 13,
                            CareerPathId = 2,
                            Description = "Implement client-side routing and navigation in React apps.",
                            Difficulty = 2,
                            DisplayOrder = 6,
                            EstimatedHours = 10,
                            Name = "React Router"
                        },
                        new
                        {
                            SkillNodeId = 14,
                            CareerPathId = 2,
                            Description = "Connect frontend applications to backend APIs using HTTP clients.",
                            Difficulty = 2,
                            DisplayOrder = 7,
                            EstimatedHours = 14,
                            Name = "API Integration"
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("University")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            ProfileId = new Guid("33333333-3333-3333-3333-333333333333"),
                            GPA = 3.5m,
                            GithubUrl = "https://github.com/demo",
                            Major = "Software Engineering",
                            University = "FPT University",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@career.com",
                            FullName = "System Administrator",
                            PasswordHash = "AQAAAAIAAYagAAAAEPJIP02MeRxP8l+CpoOY6pVMkmQIN7ld9iJtMl9x1GRoDJ6zGwdNwdGpMkAOmG/wGw==",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@career.com",
                            FullName = "Demo Student",
                            PasswordHash = "AQAAAAIAAYagAAAAEAfVa3S4ro2yj/3hgkVlmHMjtgqGRU8jwSU1Uegq6m7sROZtvVMHizvNjlwL1Hi5ew==",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.UserCareerPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerPathId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CareerPathId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCareerPaths", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerPathId = 1,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.UserSkill", b =>
                {
                    b.Property<int>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserSkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserSkillId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SkillName")
                        .IsUnique();

                    b.ToTable("UserSkills", (string)null);

                    b.HasData(
                        new
                        {
                            UserSkillId = 1,
                            SkillName = "C#",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            UserSkillId = 2,
                            SkillName = "ASP.NET Core",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            UserSkillId = 3,
                            SkillName = "SQL Server",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            UserSkillId = 4,
                            SkillName = "REST API",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.LearningResource", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.SkillNode", "SkillNode")
                        .WithMany("LearningResources")
                        .HasForeignKey("SkillNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillNode");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.PortfolioProject", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.User", "User")
                        .WithMany("PortfolioProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.RoadmapProgress", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.SkillNode", "SkillNode")
                        .WithMany("RoadmapProgresses")
                        .HasForeignKey("SkillNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerPlatform.Domain.Entities.User", "User")
                        .WithMany("RoadmapProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillNode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.SkillNode", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.CareerPath", "CareerPath")
                        .WithMany("SkillNodes")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerPath");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("CareerPlatform.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.UserCareerPath", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.CareerPath", "CareerPath")
                        .WithMany("UserCareerPaths")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerPlatform.Domain.Entities.User", "User")
                        .WithMany("UserCareerPaths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("CareerPlatform.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.CareerPath", b =>
                {
                    b.Navigation("SkillNodes");

                    b.Navigation("UserCareerPaths");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.SkillNode", b =>
                {
                    b.Navigation("LearningResources");

                    b.Navigation("RoadmapProgresses");
                });

            modelBuilder.Entity("CareerPlatform.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("PortfolioProjects");

                    b.Navigation("RoadmapProgresses");

                    b.Navigation("StudentProfile");

                    b.Navigation("UserCareerPaths");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
